export const SUBMIT_TEXT = 'SUBMIT_TEXT'
export const SAVE_PAGE = "SAVE_PAGE"
export const SAVE_STATE = "SAVE_STATE"
export const LOAD_STATE = "SAVE_STATE"




//actions for addbox options
export const BOX_CHANGE = "BOX_CHANGE"
export const ADD_MELEEWEAPON = "ADD_MELEEWEAPON"
export const ADD_RANGEDWEAPON ="ADD_RANGEDWEAPON"
export const ADD_ARMOR = 'ADD_ARMOR'
export const ADD_AUGMENTATION = 'ADD_AUGMENTATION'
export const ADD_CONTACT = 'ADD_CONTACT'
export const ADD_CYBERDECK = 'ADD_CYBERDECK'
export const ADD_GEAR = 'ADD_GEAR'
export const ADD_POWER = 'ADD_POWER'
export const ADD_QUALITY = 'ADD_QUALITY'
export const ADD_SKILL = 'ADD_SKILL'
export const ADD_SPELL = 'ADD_SPELL'
export const ADD_VEHICLE = 'ADD_VEHICLE'

export const REMOVE_MELEEWEAPON = "REMOVE_MELEEWEAPON"
export const REMOVE_RANGEDWEAPON ="REMOVE_RANGEDWEAPON"
export const REMOVE_ARMOR = 'REMOVE_ARMOR'
export const REMOVE_AUGMENTATION = 'REMOVE_AUGMENTATION'
export const REMOVE_CONTACT = 'REMOVE_CONTACT'
export const REMOVE_CYBERDECK = 'REMOVE_CYBERDECK'
export const REMOVE_GEAR = 'REMOVE_GEAR'
export const REMOVE_POWER = 'REMOVE_POWER'
export const REMOVE_QUALITY = 'REMOVE_QUALITY'
export const REMOVE_SKILL = 'REMOVE_SKILL'
export const REMOVE_SPELL = 'REMOVE_SPELL'
export const REMOVE_VEHICLE = 'REMOVE_VEHICLE'

//fetch actions

export const ITEM_HAS_ERRORED = 'ITEM_HAS_ERRORED'
export const ITEM_IS_LOADING = 'ITEM_IS_LOADING'
export const ITEM_FETCH_SUCCESS = 'ITEM_FETCH_SUCCESS'